### ISSUE TITLE
Doesn't recognize steam controller through steam link

### ISSUE THREAD

**Issue by Pendragon55555** [FrogTheFrog/steam-gyro-for-cemuhook#10]
I don't know if it is possible, but it would be great if the app could use a controller that is being used through the new steam link app or an actual steam link.

**Comment by FrogTheFrog** [comment]
@Pendragon55555 Sorry for the late reply, but currently it is not possible to Steam Controller through Steam Link (need to figure out protocol). However, I'll try to see into this during my free time.

**Comment by FrogTheFrog** [comment]
I tried it and still failed 😞. I can't figure out how steam link is sending motion data (I managed to get other data). Giving up on it unless someone wants to do a PR.

**Comment by smrq** [comment]
I'm interested in digging into this.  How did you get any data at all?  I'm not seeing any HID devices for controllers connected via Steam Link, which leaves me wondering how the data is being streamed at all.
