### ISSUE TITLE
can't find executable

### ISSUE THREAD

**Issue by MRUser35** [FrogTheFrog/steam-gyro-for-cemuhook#11]
is there something i'm missing? i can't find the executable anywhere in the files.

**Comment by FrogTheFrog** [comment]
@MRUser35 What do you mean? You can't find a download link or what?

**Comment by MRUser35** [comment]
you wrote "Drag executable anywhere you want and launch it" and i don't understand what executable you meant because there isn't any in the file that i got from the download.

**Comment by FrogTheFrog** [comment]
You must have downloaded source code. Unless you want to build app yourself, you should check the [release](https://github.com/FrogTheFrog/steam-gyro-for-cemuhook/releases) page.

**Comment by MRUser35** [comment]
oh... now i feel stupid

**Comment by MRUser35** [comment]
but thanks for the help
