### ISSUE TITLE
Gyro doesn't work with steam overlay

### ISSUE THREAD

**Issue by Diegorro98** [FrogTheFrog/steam-gyro-for-cemuhook#15]
Hi, I just bought the Steam Controller and downloadede this awesome program so I'm a Little bit noobie here hehe
Well, the issue is, when I open cemu without Steam, gyro Works cool, but when I open with Steam (I don't rly open Cemu, I open this bat file converted to exe )
[Cemu for Steam Controller.zip](https://github.com/FrogTheFrog/steam-gyro-for-cemuhook/files/2650541/Cemu.for.Steam.Controller.zip)
I open everything as an admin, but gyro doesn't work.
I've seen that some people sugest to use "Also use for butons/axes" from GamePad motion source, but I don't like too much the controls.
I'm doing something wrong to get steam overlay + cemu + gyro work together, or this is imposible?
Thx (and nice work with this program, I love it!)

**Comment by FrogTheFrog** [comment]
Hey,

what version of this app are you using? Try pre-release one, if you haven't already. Last time I've played with Cemu (~9 months ago) it worked fine. I no longer have Windows installed so I can't really test it myself. Also try using wire instead of a dongle, see if that works for some reason.

**Comment by Diegorro98** [comment]
I was using 1.3.0 because i didn't know that was pre-release, but it worked fine when I don't launch it throug Steam/Big Picture, but I just used the version 1.2.0 and I have the same problem.
I just tried using wire too, but the problem persist.

**Comment by FrogTheFrog** [comment]
@jdrr1998 Sorry for the late reply, I've just released v1.3.0 with updated dependencies and everything. Could you confirm that this is still an issue?

**Comment by FrogTheFrog** [comment]
Closing old issue.
