### ISSUE TITLE
Gyro only work if Big Picture was focused

### ISSUE THREAD

**Issue by Felina-Lain** [FrogTheFrog/steam-gyro-for-cemuhook#17]
Version Frog: 1.2.0

Observed: Frog doesn't detect any Gyro input, unless I started big picture and kept it at least semi focused. (meaning I was on bigpicture, and I used the win-key to see my taskbar and access cemu or padtest or any other soft)

Expected: for Frog to detect Gyro input all the time (if it's possible, I could be understanding this wrong)

How to reproduce:
- start frog server and start big picture (order unimportant here)
- tab out of big picture
- start padtest, or just open frog server UI to see the data. Gyro will not be working.
- re-focus on big picture, then use Win-key to be able to re-focus padtest or frog-server UI. Gyro will now be working.

I'm not sure this is an error, or if the way steam handle things make this happen
If it's an error and you need any other info, I'll be glad to help :)

**Comment by Felina-Lain** [comment]
Ok I found a workaround (or maybe it was the official steps, and I couldn't find them)

- In the cemu steam controller settings, put something on the Gyro. It can be any input (I used the directional pad, and left all the directions empty)
This forces Steam to turn ON the gyro, so the frog server can get its data.
Otherwise the gyro is OFF because it's not in use

- if you set up your steam shortcut correctly, you can now play without needing to start big picture at all :)

Now it work perfectly!

**Comment by FrogTheFrog** [comment]
I'll want to investigate this later myself, so I'll reopen this issue.

**Comment by S-C-Johnston** [comment]
Seconding the problem, using release 661a7c7. Gyro server seems not to pick up any gyro data at all unless the gyro is bound to something, which is counter to what the readme instructs. As above, I bound it to an empty directional pad and Gyro Server started to pick input up (in this case, testing using the desktop configuration for the controller so as not to need Steam Big Picture Mode to test) .

This doesn't seem to work with the wireless at all, however. Without being plugged in, cemu (1.15.0e) doesn't see the device at all, and neither does padtest (1011). When the steam controller is plugged in with usb, everything is picked up fine, though.

**Comment by FrogTheFrog** [comment]
@S-C-Johnston Could you try the latest release? Also what OS are you using?

**Comment by FerGitH** [comment]
Hi,

I have the same problem (I´m using Cemu 1.15.6c and gyro for cemuhook 1.3.1 on a win7)

The controller is recognised if connected via USB but it doesn´t work if connected using the steam dongle.

**Comment by FrogTheFrog** [comment]
Closing old issue. Reopen if you're still experiencing this issue.
