### ISSUE TITLE
Gyro not inputting correctly

### ISSUE THREAD

**Issue by Soonspl** [FrogTheFrog/steam-gyro-for-cemuhook#18]
I'm not sure why this issue happens but after about a minute or two of gameplay the gyro stops working correctly. Every time I look up it tilts to the right, and if I look down it tilts left. It's a nightmare playing any game with motion support, happens with every controller I've tried. I thought it could've been an error with betterjoy with my switch pro controller, but it still happens with DS4Windows; so my last guess is that it's this.  Been having this issue for over a year now, ever since I first tried it.

**Comment by FrogTheFrog** [comment]
Sorry for the late reply, but if it happens with every controller, isn't it a cemu or cemuhook issue?

**Comment by FrogTheFrog** [comment]
Closing old issue.

**Comment by DanteDraconi** [comment]
Sorry for commenting on an old/closed issue, perhaps I should open a new one.

I've been having exactly the same issue with a Steam Controller, looking up or down tilts to the right and left respectively. Even laying the controller flat on a table it tilts as bad as 45º to either side.
Sometimes it seems to fix itself after laying the controller down and alt-tabbing out, other times needs a restart. I don't really know when it gets fixed or breaks again.

**Comment by FrogTheFrog** [comment]
@DanteDraconi That's the problem with steam controller itself - it tends to drift after some point. Steam decided to "solve" this problem by resetting motion data while it is not being moved for some time.  There is no real fix for this unfortunately :/.

**Comment by DanteDraconi** [comment]
Damn... I've never used motion controls with it before so didn't know about it. Thanks for your input and the workaround
