### ISSUE TITLE
steam-gyro-for-cemuhook.exe terminates itself/crash - RangeError

### ISSUE THREAD

**Issue by DerKuro** [FrogTheFrog/steam-gyro-for-cemuhook#20]
Description:
see screenshot and log file.

The error occurs after a while (fresh boot) of normal use. Consecutive starts of the program after the initial error yield in immediate errors if the steam controller is powered on and connected and
set as motion source in cemuhook. 
Rebooting the PC helps but as stated above only lasts a little while (maybe 2 minutes).

the negative sign of "value" (see log) indicate a false 'signed/unsigned' variable declaration (or conversion I guess?)

![screenshot](https://user-images.githubusercontent.com/39744870/52461543-c18b3200-2b6f-11e9-89ab-cb36c74d96c4.png)

Log file:
[sgfc.log](https://github.com/FrogTheFrog/steam-gyro-for-cemuhook/files/2843814/sgfc.log)

**Comment by FrogTheFrog** [comment]
This is what I get for only testing with testpad 😄 Bug confirmed and replicated. Gonna fix this ASAP.

**Comment by FrogTheFrog** [comment]
I actually managed to replicate it once by sheer luck and can't do it again. Do you have to follow some kind of specific order?

**Comment by DerKuro** [comment]
I started cemu (with cemuhook) first. then steam-gyro. After the error it didnt't matter which order I chose. Immediate crash after starting Steam-gyro but only if there is input (moving the controller).

Maybe it is on cemuhooks end, since everything works if I set "GamePad motion source" in cemuhook to default or anything else than the connected Steam Controller (in this case DSU1). 
As soon as I set the motion source to DSU1 -> RangeError pops up.

I will now try running Steam-gyro first and cemu afterwards.

**Comment by FrogTheFrog** [comment]
Nope, it's on my end. I even managed to trace back where it was producing a negative number where positive is expected, I then ran out of luck as it started working as intended and I could not get to the root cause.

**Comment by DerKuro** [comment]
I see. So far it is working (not sure if starting Steam-gyro first helped or if it pure luck). Is there anything I can help you with if I manage to reproduce the error again?

**Comment by FrogTheFrog** [comment]
Unfortunately no, I'll just have to try my luck.

**Comment by FrogTheFrog** [comment]
I lucked out on first try, fixed the issue hopefully.
