### ISSUE TITLE
Custom port keeps reverting to standard.

### ISSUE THREAD

**Issue by Dezrox** [FrogTheFrog/steam-gyro-for-cemuhook#21]
Every time I start up the .exe, I get the following error:

Error: bind EADDRINUSE 127.0.0.1:26760
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I have altered cmuhook.ini to use 26761 port, and everything works fine when I reload the server with the matching port. My problem is that when I start up the .exe again, it reverts to 26760. This causes an error every time.

I don't have a .json file to edit as you suggested in a previously closed issue.
Any thoughts?

**Comment by FrogTheFrog** [comment]
Now that's a strange issue. If no other errors are showing up, then I don't know what could be wrong. Could you let me take a look over teamviewer and perhaps debug it on your PC?

**Comment by Dezrox** [comment]
Hey, I don't have tons of time in the evening to troubleshoot with you (I'm East-Coast USA), but I could try. You'd have to help me out with teamviewer though, not sure what that is.

Only other detail that I left out from before is that when I started the .exe for the first time Windows gives me a warning:

![image](https://user-images.githubusercontent.com/24260053/55367264-3157d200-54ba-11e9-9ead-7001890877ba.png)
(not sure if some security setting is preventing the .json file from being created... I am running as Admin)

In the latest release, I only downloaded the .exe file, do I need any of the other files from Source Code?
Could you just provide a .json file for the .exe to target?

Thanks!

**Comment by FrogTheFrog** [comment]
Closing old issue. Reopen if you're still experiencing this issue.
