### ISSUE TITLE
Steam controller not detected in Bluetooth low energy mode

### ISSUE THREAD

**Issue by rgmsilva** [FrogTheFrog/steam-gyro-for-cemuhook#22]
First of all, I appreciate your work with this app, it has been invaluable to me and many others,  so thank you for all your work.
The steam controller is not detected in the application when in BLE mode, it works fine wired.
I cannot test with the original dongle as it has gone to electronics heaven.
I am running the newest version of the steam controller firmware.
*EDIT I tried earlier versions, it was also not showing up on the devices tab, all it showed was my keyboard.

**Comment by Crono141** [comment]
I can confirm that BLE mode on steam controller doesn't work.

**Comment by Windsinni** [comment]
I can't use gyro with BLE mode either
Is there any solution?

**Comment by NickZ** [comment]
I took a look at this, but it uses a completely different protocol that hasn't been reverse engineered by anyone yet. Plus, it's currently only in beta right now, and the gyro resolution is pretty low compared to using it wired or with the dongle. I wouldn't recommend it.

**Comment by FrogTheFrog** [comment]
Also, to add to what @NickZ said, it might require to install separate BLE drivers for Windows 10. A pull request is welcome.

**Comment by FrogTheFrog** [comment]
I'm archiving this project and therefore closing this issue.
