### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by NickZ** [FrogTheFrog/steam-gyro-for-cemuhook#25]
I had tried adding Mac support to my PR #24, but a few things are holding this back:

1. node-hid needs to be updated to use hidapi 0.9, as the interface numbers weren't populating properly in the device listing prior to that. node-hid on `master` currently uses that version, but not the npm release one.
2. hidapi on mac currently only opens the device in exclusive mode, which leads to a lot of deadlocks while trying to use this. There's a bug report here: https://github.com/libusb/hidapi/issues/27

**Comment by FrogTheFrog** [comment]
I'm archiving this project and therefore closing this issue.
