### ISSUE TITLE
Can't get device connected

### ISSUE THREAD

**Issue by Detrixukaon58** [FrogTheFrog/steam-gyro-for-cemuhook#27]
every time I try to use the software, i can't get it to connect. This is what i see whenever i follow the instructions on how to use it.
![Screenshot (91)](https://user-images.githubusercontent.com/20668560/67611521-fbe63f00-f791-11e9-8aa9-502cf3fd0e19.png)

**Comment by FrogTheFrog** [comment]
Can you connect it to https://files.sshnuke.net/PadTest_1011.zip?

**Comment by FrogTheFrog** [comment]
Also try v1.3.3 of this app, you should see green wifi icon in the UI if connection to something is established.

**Comment by Detrixukaon58** [comment]
I have tried to use the pad test app, but it doesn't work. 
Does this software only work for steam controllers or does it work with the steam controller mapper, that lets you use other controllers on steam games?

**Comment by FrogTheFrog** [comment]
It works only with a steam controller.

**Comment by Detrixukaon58** [comment]
Ok, thanks. Sorry for any inconvenience.
