### ISSUE TITLE
Support selecting from multiple controllers

### ISSUE THREAD

**Issue by NickZ** [FrogTheFrog/steam-gyro-for-cemuhook#29]
Support selecting from multiple controllers when detecting multiple active.

I mostly want to add this in anticipation of adding Dualshock 4 support, but I am running into issues refactoring it to do so. @FrogTheFrog I was just curious, did you have any work on this so far?

**Comment by FrogTheFrog** [comment]
I had this functionality before, but I've removed it after refactor :thinking:

**Comment by Cheerpipe** [comment]
Hi and first off all thanks for the great work. This app is the only hope for us SC owners.

Any chances of get multi controller support? I have two SC so i can help with debug and test.

**Comment by bindi** [comment]
Can we expect to see multiple controller support anytime soon? I've been using a steam controller to play BOTW and it works fantastically, however, I would like to play some games with my friends such as Mario Party, which requires a gyro (to act as a wiimote, iirc). My 4 steam controllers are currently limited to older non-gyro/wiimote games :-(

**Comment by MRcoin2** [comment]
@FrogTheFrog  are you still working on this project?

**Comment by FrogTheFrog** [comment]
> @FrogTheFrog are you still working on this project?

Unfortunately, not really. I might fix some bugs, but no new features since I no longer have Steam Controller 😕

**Comment by FrogTheFrog** [comment]
I'm archiving this project and therefore closing this issue.
