### ISSUE TITLE
Hello! im having an issue with getting steamgyro to launch

### ISSUE THREAD

**Issue by Bobbynofoot** [FrogTheFrog/steam-gyro-for-cemuhook#3]
So when i run your program I get this error, Error: bind EADDRINUSE 127.0.0.1:26760
and it dies instantly. Any idea why? or do you need the whole log?

**Comment by FrogTheFrog** [comment]
@Bobbynofoot Address `127.0.0.1` is in use. Try changing it to `127.0.0.2`, etc. in generated json file. If it works, you'll also need to change server address in cemuhook settings.

**Comment by FrogTheFrog** [comment]
@Bobbynofoot Did you fix this issue?

**Comment by Bobbynofoot** [comment]
oh wow that was fast, sorry i haven't been around my PC in the last few
days. This seems to have fixed the issue, thanks man!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
