### ISSUE TITLE
Not connecting to Steam Controller

### ISSUE THREAD

**Issue by frogsatan** [FrogTheFrog/steam-gyro-for-cemuhook#30]
The app seems to no longer be able to find the Steam Controller. The UDP icon stays red, the tooltip reads "disconnected".
The Steam Controller is connected via cable and works fine in all other apps. I've tried switching to different cables, different USB ports, re-downloading the app, restarting the PC, but to no avail.
It seems going back to 1.3.1 seems to fix it.

**Comment by Hinkiii** [comment]
Thank you for this I was just having issues with that

**Comment by Blargh14** [comment]
Ah, I wouldn't be giving any new information then.
1.3.0/1.3.1 gives #23 issue for me, onward doesn't find the controller. Currently using 1.2.0 and it works fine.
Thanks FrogTheFrog for the program!

**Comment by FrogTheFrog** [comment]
@frogsatan, @Hinkiii, @Blargh14 Sorry for the late reply. It should fixed in 1.3.4 and if it is please close the issue.

@Blargh14 Could you additionally verify that you do not encounter issue #23 😄 ?

**Comment by Blargh14** [comment]
> @Blargh14 Could you additionally verify that you do not encounter issue #23 😄 ?
>
Well wasn't late for me at least. Just downloaded it and used padtest, everything seems to be working great so far! Nice shiny UI and everything. #23 didn't occur. Thanks!
