### ISSUE TITLE
App crashes if you open the UI then hide it

### ISSUE THREAD

**Issue by download13** [FrogTheFrog/steam-gyro-for-cemuhook#31]
It seems that when you open the UI, the backend starts periodically sending `connection-status` updates to the frontend (among others, but that's the one crashing it for me).

If you click "Hide", and wait 5 seconds for it to destroy the renderer it'll crash with the error `Object has been destroyed`.

I think the problem is that the `connection-status` updates keep getting sent even when the destination no longer exists. I tried to fix it myself, but I don't really understand how the IPC system works well enough to know what I'm doing.

In the "sending" code, a check that ensures the destination still exists before passing the message would probably fix this though.

**Comment by FrogTheFrog** [comment]
@download13 Sorry for the late response, it was worse than that 😄 Hopefully, it should be fixed now. Could you check out 1.3.4 and close this issue if it's solved for you?

**Comment by download13** [comment]
Looks good, thanks!
