### ISSUE TITLE
App is using GPU explicitly (on Windows at least)

### ISSUE THREAD

**Issue by neico** [FrogTheFrog/steam-gyro-for-cemuhook#33]
I don't have an issue per se with it doing so,
but given the simplicity of what this application provides I've got curious why it's listed in Nvidia's GPU activity list.

As far as I can see it this is using a website as UI, requiring something like CEF.
I however don't see anything that would actually require "Hardware Acceleration".
Can this either have the usual "Disable Hardware Acceleration" checkbox known from browsers or disable it outright? (unless it impacts something crucial of course)

**Comment by FrogTheFrog** [comment]
I agree, I don't see why it should be in GPU list while the UI process itself does not exist 🤔.

Anyway, since I'm not doing fancy graphics I see no reason why this can't be disabled for the whole app. Once, the 1.3.5 builds are released, I will close this issue.
