### ISSUE TITLE
CEMU 1.18.0 & 1.18.1 using new API DSUClient works with lag

### ISSUE THREAD

**Issue by FirefoxinHell** [FrogTheFrog/steam-gyro-for-cemuhook#35]
I tried to test new built in API for Motion on input settings with the dsu
steam-gyro-for-cemuhook

the problem its self, no rumble support anymore and big Lag, all the controll take long time to response, more than a second i think.

using the old cemuhook and xinput works perfect like always

VERSION 1.18.0 have the bug
VERSION 1.18.1 have the bug

i dont know if the problem came from emulator or the DSU.

**Comment by FrogTheFrog** [comment]
I'm afraid that's the issue with Cemu itself, there's nothing I can do about it right now :/. Just gotta wait,

**Comment by FirefoxinHell** [comment]
thast what I think,  sorry for bother you with this,i think we need to whait a new release 
by the way, great software thanks a lot for your works, use it for dolphin too and its works flawless, the only think its drive me crazy its how to separate motion of to real controller on one Steam controller, like Zelda Skywards needs, its use wiimote and nunchuck with motion both at the same time, for attack, its the only problem I detect
i think its a limitation of the emulator too, not your problem.
thanks a lot for your support and your hard work, Cheers from Argentina.
by the way, my english its NOT the best in the world, sorry.
