### ISSUE TITLE
Cemu 1.20.0b no connection!

### ISSUE THREAD

**Issue by optical10** [FrogTheFrog/steam-gyro-for-cemuhook#36]
Cemu 1.19.3 was fine yesterday steam updated today as well as Cemu to this patreon Cemu 1.20.0b build then steam controller doesn't connection in cemu but the "FrogTheFrog/steam-gyro-for-cemuhook" shows a connection. Steam shows a connection too but cemu doesn't?

**Comment by FrogTheFrog** [comment]
I've just checked with public release and it still works, but for some reason controller configuration was reset. Verify that controller input is set to XInput, and etc., but NOT to DSUInput.
