### ISSUE TITLE
steam-gyro.json won't generate ever if an error is encountered during application start

### ISSUE THREAD

**Issue by cheatfreak47** [FrogTheFrog/steam-gyro-for-cemuhook#37]
users with the default port in use already (such as by scp-service) encounter a problem where steam-gyro.json is never able to generate, even if the server restarts on another port or local address that isn't in use afterwards

**Comment by FrogTheFrog** [comment]
Hey, try the 1.3.6 release. Should be fixed now :thinking:

**Comment by cheatfreak47** [comment]
confirmed fixed, nice work!
