### ISSUE TITLE
Connection Icon Flashes Orange/Green

### ISSUE THREAD

**Issue by Thornskade** [FrogTheFrog/steam-gyro-for-cemuhook#38]
It keeps changing from "Connected" to "Device connected | No UDP connection" every second or so. Is that normal?

I'm asking because I can't get it to work in Yuzu. The emulator says that it "Successfully received data from the server" when I click on "Test", and yet, when it asks me to "Shake!", I can't get the motion to map. It should say "Motion 0" but nothing happens.

**Comment by FrogTheFrog** [comment]
The flashing icon is my fault. The protocol specifies a 5 sec. client notification window (that they are still listening). Cemu notifies the app every 1 sec., whereas the yuzu does this every 3 sec. I will fix it by increasing the said window from 1 sec. to 5 secs.

How can I get yuzu to ask me to shake it?

**Comment by FrogTheFrog** [comment]
I think I've found the problem, time to find out if it's me or yuzu who did boo boo.

**Comment by Thornskade** [comment]
Thank you so much for looking into this.

As for Yuzu, in the controller config under the image of the Pro Controller there's a bind called "Motion 1", that's the one where you are supposed to shake your controller to bind it.

**Comment by FrogTheFrog** [comment]
I fixed the bug where I was sending data way too many times. Alas, this changes nothing apart from less clutter in yuzu's log. However, due to this bug, I'm 100% sure that it is indeed receiving motion data constantly.

Now this will be a very stupid question, but aren't the assign buttons intended for "physical" devices? If I uncheck the "motion" checkbox for emulated motion, I can still "shake" it 🤔 :
![image](https://user-images.githubusercontent.com/22381748/94302947-bc157200-ff75-11ea-897b-63405fcf3bd7.png)

**Comment by FrogTheFrog** [comment]
You can enable logging in Yuzu to see what a mess the current release is. The new release fixes it.

**Comment by Thornskade** [comment]
I will try it once I'm home, I'm away for the weekend or at least till Saturday evening, central European time

And yes, you can click on "Shake!" without enabling motion controls and assign a physical button – but with motion controls enabled, the field should say "Motion 0" after you've shaken your controller. That will be your motion mapping.

**Comment by FrogTheFrog** [comment]
This is should be fixed by https://github.com/yuzu-emu/yuzu/pull/4727.

**Comment by FrogTheFrog** [comment]
@TheThurbo Until the fix is merged, just go to `%appdata%\yuzu\config\qt-config.ini` and set `player_0_motionleft` to
```
player_0_motionleft\default=false
player_0_motionleft="pad_index:0,engine:cemuhookudp,motion:5,port:26760,ip:127.0.0.1"
```

**Comment by german77** [comment]
Please address the comment on yuzu-emu/yuzu#4727 so it can be merged

**Comment by FrogTheFrog** [comment]
@german77 Sorry, but what comment? The CLA is already signed.

**Comment by Thornskade** [comment]
@FrogTheFrog Thank you, that works!

**Comment by german77** [comment]
Sorry, I did not notice that it wasn't visible for everyone. It should be visible now.

**Comment by FrogTheFrog** [comment]
Yuzu merged the fix to mainline, so this can be closed.
