### ISSUE TITLE
Ubuntu 20.04: buttons/sticks or motion.  Not both at the same time.

### ISSUE THREAD

**Issue by Davidian1024** [FrogTheFrog/steam-gyro-for-cemuhook#45]
Hello,

I'm trying to configure this to work with the Yuzu emulator under Ubuntu 20.04.

I'm able to launch the AppImage and I can see it listening on UDP port 26760.  I see my steam controller getting recognized by steam-gyro-for-cemuhook.  And I can see accel and gyro data as i move the controller around.

When I launch the Yuzu emulator I'm able to select the steam controller and configure it to connect to local UDP port 26760.  And motion controls work in game.

Unfortunately nothing else works.  What I've been having to do is start a game with steam-gyro-for-cemuhook not yet running.  Then play the game until I get to a point where I need motion controls.  Then I start steam-gyro-for-cemuhook and configure the emulator to use it as a motion provider.  At that point all the buttons and sticks are no longer available to be configured.

So at the moment I can only seem to use buttons/sticks or motion.  Not both at the same time.

There's a tool called jstest-gtk I've used to test controllers/joysticks under linux quite alot and it gives me a little insight as to what's going on.  When steam-gyro-for-cemuhook is running that tool seems to take ownership of the steam controller.  jstest-gtk can't see the steam controller as a configurable controller while steam-gyro-for-cemuhook is connected to the steam controller.  The same seems to be true for the Yuzu emulator.

Is there a way to work around this?

Thanks,
Dave

**Comment by FrogTheFrog** [comment]
Hello,

unfortunately I don't know a workaround for this. In the past I've used this app in combination with steam and it seemed to work for cemu (never noticed this issue in the first place).

I no longer own a steam controller, so I'm afraid you're on your own :disappointed:

**Comment by FrogTheFrog** [comment]
I'm archiving this project and therefore closing this issue.

PS. if you're on linux please take a look at https://github.com/v1993/evdevhook.
