### ISSUE TITLE
Judder

### ISSUE THREAD

**Issue by angusmglfraser** [FrogTheFrog/steam-gyro-for-cemuhook#46]
I've been using this on CEMU, and I've noticed that there's a constant subtle juddering making precise aiming a little more difficult. It feels like the polling rate on this might be lower than what the Steam controller normally does when used via SteamInput.

I haven't been getting this issue when using other controllers with cemuhook.

**Comment by FrogTheFrog** [comment]
Hello, sorry for the late reply as I did not notice this issue. It's a known issue and the post-processing needs to be done on the sensor-data consumer side. Nothing really can be done about this.

I'm archiving this project and therefore closing this issue.
