### ISSUE TITLE
[Feature request] SteamDeck's gyro support

### ISSUE THREAD

**Issue by S1lent-Gh0st** [FrogTheFrog/steam-gyro-for-cemuhook#47]
Hi
I've tested SteamDeck's gyro using AppImage release however software cannot pick it up. Is there a way to add support for SteamDeck's gyro?
If you need any logs or files I'll happily provide them.

**Comment by FrogTheFrog** [comment]
Hello,

unfortunately this was developed for SteamController and will not work with SteamDeck (still waiting, Q2 :cry:).
I will not be adding the implementation for this.

With that said, I know that on linux most of the time the gyro data is exposed on `/dev/input`. This usually can be verified in system settings (this is how it looks for my dualsense controller):
![image](https://user-images.githubusercontent.com/22381748/156879538-7211cd6a-84d9-48a0-8ab7-b956d26bbdb4.png)

If that's the case, I would like to direct you to https://github.com/v1993/evdevhook - after some fiddling around you should be able to get it working.
