### ISSUE TITLE
Gyro will not work unless the "Steam Gyro for Cemuhook" windows is visible and focused.

### ISSUE THREAD

**Issue by tacticalcraptical** [FrogTheFrog/steam-gyro-for-cemuhook#6]
Steam controller gyro will not work unless the "Steam Gyro for Cemuhook" window is open, visible and focused. If the Cemu windows is focused or fullscreen, the gyro stops responding.

I have tried to run Cemu and Steam Gyro for Cemuhook as administrator.  Tried various version combinations of Cemu and Steam Gryo. 

I am on Windows 7 64-bit, latest version.

Thanks.

**Comment by FrogTheFrog** [comment]
Can you try using [padtest](https://sshnuke.net/cemuhook/padudpserver.html)? This app reads data directly from Steam controller, it should not matter whether UI is open or not.

**Comment by tacticalcraptical** [comment]
Sorry it took so long to get back. It does seem to work fine in PadTest, even when the Steam Gyro app is hidden. So I guess it's something with the Cemu setup maybe. I have tried tweaking a lot of the settings in there and matched them exactly to the ReadMe. What could I be missing?

**Comment by tacticalcraptical** [comment]
This is my cemuhook.ini
[Input]
motionSource = DSU_545200BBAC15
motionSourceIsBtnSource = false
serverIP = 127.0.0.1
serverPort = 26760

One thing I just noticed, if I have the Steam Devices tab open, I can see the gyro values changing as I move the control but as soon as the Cemu windows is focused, the numbers stop changing, if I focus any other window, they will continue react.

**Comment by FrogTheFrog** [comment]
Just for testing purposes: exit Steam and select "Also use for buttons/axes" in Cemu. Also, always use motion source "By slot". MAC id is random every time you restart this app. 

Launch any game and test out controller. We should see if it's a problem with Cemu or Steam.

**Comment by tacticalcraptical** [comment]
Let me clarify, you're saying have Steam closed completely, turn on "Also use for buttons/axes" and run Cemu with Steam still closed?  I tried this but Steam Gyro for Cemuhook won't even find the controller if Steam isn't running, shows "disconnected" in Cemu and PadTest won't read it either.

**Comment by FrogTheFrog** [comment]
@tacticalcraptical Could you reach me on discord (FrogTheFrog#1801). It would be faster to communicate this way.

**Comment by tacticalcraptical** [comment]
I am so sorry, I have left town for the week on vacation. I could next week if you are still wanting to look into it.  Thanks for the help!

**Comment by FrogTheFrog** [comment]
@tacticalcraptical No worries, just find me when I'm online and I'll help :)

**Comment by FrogTheFrog** [comment]
If I remember correctly, it was a Windows 7 issue.
