### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pharmville** [FrogTheFrog/steam-gyro-for-cemuhook#8]
I figure that it can't hurt to ask. Can this software be modified to work with steam controllers which are connected to the steam link? Or even ps4 controllers connected to steamlink? I want to play from my tv a few rooms away, instead of my pc monitor.

**Comment by FrogTheFrog** [comment]
Technically it can be done. I tried to do it in the past, however I did not manage to decipher gyroscope data from incoming data stream. Therefore I just gave up as I have other things to do. Unless someone manages to figure out steam link's data protocol, I'm not pursuing this matter any further.

One thing you can do is to connect your Steam Controller to a laptop and steam data via laptop to your gaming pc via LAN (maybe internet too, but I haven't tested this).
