### ISSUE TITLE
'Steam Gyro encountered a fatal error!'

### ISSUE THREAD

**Issue by Don-Vicente** [FrogTheFrog/steam-gyro-for-cemuhook#9]
Hi there, I'm new here and just wanted to say thanks for posting this app for the steam controller!
Unfortunately I've run into an issue where I can't seem to restart the server for the program to work.
Upon starting the application I'm met with the error:

`error: Error: bind EADDRINUSE 127.0.0.1:26760`

After changing the server address to 127.0.0.2, etc. within the program as well as in the generated .json file (as you've instructed) I then opened the program again which provided me with a new error:

```
2018-04-27T16:46:42.634Z - error: FATAL ERROR!
2018-04-27T16:46:42.635Z - error:  
[ { keyword: 'type',
    dataPath: '.silentErrors',
    schemaPath: '#/properties/silentErrors/type',
    params: { type: 'boolean' },
    message: 'should be boolean' } ]
```

I don't know where I'm going wrong so any feedback and help would be greatly appreciated.

**Comment by FrogTheFrog** [comment]
@Don-Vicente Can you post your `.json` file?

**Comment by Don-Vicente** [comment]
Definitely, my `.json` file looks like this:

```
{
    "enabledFilters": {
        "accelerometer": true,
        "gyro": false
    },
    "filters": {
        "accelerometer": [
            {
                "coefficients": [],
                "deviation": {
                    "max": null,
                    "min": null
                },
                "filterAllAtOnce": null,
                "type": null
            }
        ],
        "gyro": []
    },
    "modifierVersion": null,
    "server": {
        "address": "127.0.0.2",
        "port": 26760
    },
    "silentErrors": null
}
```

**Comment by FrogTheFrog** [comment]
@Don-Vicente You're using 1.3.0, which has broken `settings` UI. Which means you have to edit `json` file manually or else it will corrupt it. Delete `json` file and a new one will be generated. Then you can edit server address.

**Comment by Don-Vicente** [comment]
Wow, you were spot on! 
The server connected immediately after I did what you said and manually changed it within the `.json` file. 
In order to change my port, and filter options will I have to do the same and edit them within file too?
Regardless, thanks Frog for the speedy reply and excellent help!

**Comment by FrogTheFrog** [comment]
Yup, in 1.3.0 you have to edit `json` file manually and then restart the app.
